version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
    - cd my-app/
  build:
    commands:
      - echo Build started on `date`
      - mvn test 
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
      - ls -la 
      - la -la ../
artifacts:
  files:
    - my-app/target/my-app-1.0-SNAPSHOT.jar
    - my-app/appspec.yml
  discard-paths: yes